trigger:
  branches:
    include:
    - refs/heads/master
jobs:
- job: Job_1
  displayName: Install & build
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: NodeTool@0
    displayName: Use Node 16.13.2
    inputs:
      versionSpec: 16.13.2
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: client
      verbose: false
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      workingDir: client
      verbose: false
      customCommand: run build
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
...
